### ISSUE TITLE
"'NoneType' object has no attribute 'split'" when making a media post

### ISSUE THREAD

**Issue by JPLeBreton** [halcy/Mastodon.py#216]
I have a mastodon bot (source at https://heptapod.host/jp-lebreton/vsbot ) that's been running without issue from my Raspberry Pi for a good couple of years now. Yesterday I upgraded the Pi from Raspbian Jessie to Buster (going from Python 3.4 to 3.7), and the bot script seems to do everything fine except when it gets to posting the image it's generated at the end. Below is the error text I see. Happy to provide more info. This also happens when I try to run the same code on my desktop, which is running Manjaro latest with Python 3.8.

```
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/mastodon/Mastodon.py", line 3337, in __api_request
    if hashlib.sha256(",".join(base_url.split("//")[-1].split("/")[0].split(".")[-2:]).encode("utf-8")).hexdigest() in \
AttributeError: 'NoneType' object has no attribute 'split'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "vsbot.py", line 364, in <module>
    m = masto_api.media_post(vsimage.OUTPUT_IMAGE_FILENAME)
  File "<decorator-gen-105>", line 2, in media_post
  File "/usr/lib/python3.8/site-packages/mastodon/Mastodon.py", line 102, in wrapper
    return function(self, *args, **kwargs)
  File "/usr/lib/python3.8/site-packages/mastodon/Mastodon.py", line 2500, in media_post
    return self.__api_request('POST', '/api/v1/media',
  File "/usr/lib/python3.8/site-packages/mastodon/Mastodon.py", line 3347, in __api_request
    raise MastodonNetworkError("Could not complete request: %s" % e)
mastodon.Mastodon.MastodonNetworkError: Could not complete request: 'NoneType' object has no attribute 'split'
```

**Comment by JPLeBreton** [comment]
I think I managed to fix (or work around?) this issue on my side. I provided a "api_base_url" argument with the instance the account is on to the API constructor, and it was able to post successfully.
https://heptapod.host/jp-lebreton/plotbot/-/commit/2fb11de105eae86f30a0f85343a6ddb70c7e69cb
If the bug reported above isn't legitimate based on current usage of this API wrapper, feel free to close it. If it is legitimate failure case, a clear error message would be helpful.
Thanks for creating this project! I've had zero issues with it otherwise and the docs are helpful.

**Comment by halcy** [comment]
that's honestly quite weird and should not happen, and I'll have to look into it, maybe something changed with how defaults work in 3.7, or maybe the debian maintainer took the default out. It's a good idea to explicitly give the base URL, though, in any case.

Do not really have time to triage this presently but will leave issue open so I don't forget (or in case somebody else has that problem / wants to fix)

**Comment by arittner** [comment]
Hello @JPLeBreton 

The __DEFAULT_BASE_URL is only used in `create_app`, if you don't pass an instance. With a given `to_file` to `create_app` the instance URL get stored.

The constructor for Mastodon does not use a default value for the instance URL. If you do not specify a URL, it can only be loaded from the file where your app registration data is located. If the URL is also missing in the file (for whatever reason) or the file could not be found, `self.api_base_url` remains empty. In this case, the described error may occur. 

Because from your commit, I can see that you included the access token and the client ID in the constructor. So in combination with a file that would normally store that, you have the credentials via the constructor and only the instance URL via the file. The file is probably no longer where you expect it to be, and thus the base_url is missing.

In my opinion, this is not a bug of Mastodon.py, but in the configuration with you. Can you please check this?

**Comment by arittner** [comment]
Hello @JPLeBreton 

Because of inactivity, I close this issue. You are welcome to re-open, if you can provide additional information.
